/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package isr;

import claces.Conexion;
import claces.cargos;
import claces.empleados;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import static java.lang.Double.parseDouble;
import static java.lang.Integer.parseInt;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */

public class Cargos extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    private PreparedStatement SentenciaSQL; 
    public Cargos() {
        initComponents();
        id.setVisible(false);
        setLocationRelativeTo(null);
        txtDescripcion.setLineWrap(true);
        txtDescripcion.setWrapStyleWord(true);
    }
 public void Limpiar(){
        txtNombre.setText(null);
        txtDescripcion.setText(null);
        txtSalario.setText(null);
            btnAgregar.setEnabled(true);
            btnModificar.setEnabled(false);
            btnConsultar.setEnabled(true);
            btnEliminar.setEnabled(false);
            btnLimpiar.setEnabled(false);
    }
    public void LimpiarTabla(){
                try 
            {
            DefaultTableModel modelo=(DefaultTableModel) tabla.getModel();
            int filas=tabla.getRowCount();
            for (int i = 0;filas>i; i++) {
            modelo.removeRow(0);
            }
            } 
            catch (Exception e) 
            {
                JOptionPane.showMessageDialog(null, "Error al limpiar la tabla");
            }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        txtSalario = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        btnAgregar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CARGOS");
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("Nombre Cargo : ");

        jLabel2.setText("Descripcion : ");

        jLabel3.setText("Salario : ");

        id.setText("ID :");

        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        jScrollPane1.setViewportView(txtDescripcion);

        try {
            txtSalario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(id))
                                .addGap(49, 49, 49)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSalario)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNombre)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(id))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Cargo", "Descripción", "Salario"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabla);
        if (tabla.getColumnModel().getColumnCount() > 0) {
            tabla.getColumnModel().getColumn(0).setMinWidth(0);
            tabla.getColumnModel().getColumn(0).setPreferredWidth(0);
            tabla.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnAgregar)
                        .addGap(18, 18, 18)
                        .addComponent(btnModificar)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addComponent(btnConsultar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar)
                    .addComponent(btnModificar)
                    .addComponent(btnEliminar)
                    .addComponent(btnConsultar)
                    .addComponent(btnLimpiar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
         btnAgregar.setEnabled(false);
        btnModificar.setEnabled(true);
        btnEliminar.setEnabled(true);
        btnConsultar.setEnabled(false);
        btnLimpiar.setEnabled(true);
        claces.cargos f=new claces.cargos();
        try {
            f.llenarTabla(tabla);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
         Limpiar();
        LimpiarTabla();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
           cargos obj = new cargos();
           claces.descuentos ob = new claces.descuentos();
            obj.setNombre_cargo(txtNombre.getText());
            obj.setDescripcion_cargo(txtDescripcion.getText());
            obj.setSalario(parseDouble(txtSalario.getText()));
            ob.setCargo(parseInt(id.getText()));
            double afp=0.00, isr=0.00, total=0.00, salario_final=0.00, salario_sinafp=0.00;
            afp= (parseDouble(txtSalario.getText()) * 0.0625);
            salario_sinafp= parseDouble(txtSalario.getText())-afp;
            if (parseDouble(txtSalario.getText())>=0.01 && parseDouble(txtSalario.getText())<=487.60)
            {
                isr= 0.00;
                total= afp + isr;
                salario_final= parseDouble(txtSalario.getText()) - afp - isr;
                ob.setAfp(afp);
                ob.setIsr(isr);
                ob.setTotal(total);
                ob.setSalario_final(salario_final);
            }
            else if (parseDouble(txtSalario.getText())>=487.61 && parseDouble(txtSalario.getText())<=642.85)
            {
                isr= parseDouble(txtSalario.getText())-487.60;
                total= afp + isr;
                salario_final= parseDouble(txtSalario.getText()) - afp - isr;
                ob.setAfp(afp);
                ob.setIsr(isr);
                ob.setTotal(total);
                ob.setSalario_final(salario_final);
            }
            else if (parseDouble(txtSalario.getText())>=642.86 && parseDouble(txtSalario.getText())<=915.81)
            {
                isr= parseDouble(txtSalario.getText())-642.85;
                total= afp + isr;
                salario_final= parseDouble(txtSalario.getText()) - afp - isr;
                ob.setAfp(afp);
                ob.setIsr(isr);
                ob.setTotal(total);
                ob.setSalario_final(salario_final);
            }
            else if (parseDouble(txtSalario.getText())>=915.82 && parseDouble(txtSalario.getText())<=2058.67)
            {
                isr= parseDouble(txtSalario.getText())-915.81;
                total= afp + isr;
                salario_final= parseDouble(txtSalario.getText()) - afp - isr;
                ob.setAfp(afp);
                ob.setIsr(isr);
                ob.setTotal(total);
                ob.setSalario_final(salario_final);
            }
            else if (parseDouble(txtSalario.getText())>=2058.68)
            {
                isr= parseDouble(txtSalario.getText())-2058.67;
                total= afp + isr;
                salario_final= parseDouble(txtSalario.getText()) - afp - isr;
                ob.setAfp(afp);
                ob.setIsr(isr);
                ob.setTotal(total);
                ob.setSalario_final(salario_final);
            }
            if(obj.guardarCargo())
            {
                    obj.guardarCargo();       
                    ob.guardarDescuentos();
                    JOptionPane.showMessageDialog(this, "Datos Guardados");
                    Limpiar();
                    LimpiarTabla();
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(this,"Verifique el nombre del cargo. Podría existir.");
                    }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
            btnAgregar.setEnabled(true);
            btnModificar.setEnabled(false);
            btnConsultar.setEnabled(true);
            btnEliminar.setEnabled(false);
            btnLimpiar.setEnabled(false);
    }//GEN-LAST:event_formWindowOpened

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
            id.setText(tabla.getValueAt(tabla.getSelectedRow(), 0).toString());
            txtNombre.setText(tabla.getValueAt(tabla.getSelectedRow(), 1).toString());
            txtDescripcion.setText(tabla.getValueAt(tabla.getSelectedRow(), 2).toString());
            txtSalario.setText(tabla.getValueAt(tabla.getSelectedRow(), 3).toString());
    }//GEN-LAST:event_tablaMouseClicked

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
            cargos obj = new cargos();
            claces.descuentos ob = new claces.descuentos();
            obj.setNombre_cargo(txtNombre.getText());
            obj.setDescripcion_cargo(txtDescripcion.getText());
            obj.setSalario(parseDouble(txtSalario.getText()));
            obj.setId(parseInt(id.getText()));
            ob.setCargo(parseInt(id.getText()));
            double afp=0.00, isr=0.00, total=0.00, salario_final=0.00, salario_sinafp=0.00;
            afp= (parseDouble(txtSalario.getText()) * 0.0625);
            salario_sinafp= parseDouble(txtSalario.getText())-afp;
            if (parseDouble(txtSalario.getText())>=0.01 && parseDouble(txtSalario.getText())<=487.60)
            {
                isr= 0.00;
                total= afp + isr;
                salario_final= parseDouble(txtSalario.getText()) - afp - isr;
                ob.setAfp(afp);
                ob.setIsr(isr);
                ob.setTotal(total);
                ob.setSalario_final(salario_final);
            }
            else if (parseDouble(txtSalario.getText())>=487.61 && parseDouble(txtSalario.getText())<=642.85)
            {
                isr= parseDouble(txtSalario.getText())-487.60;
                total= afp + isr;
                salario_final= parseDouble(txtSalario.getText()) - afp - isr;
                ob.setAfp(afp);
                ob.setIsr(isr);
                ob.setTotal(total);
                ob.setSalario_final(salario_final);
            }
            else if (parseDouble(txtSalario.getText())>=642.86 && parseDouble(txtSalario.getText())<=915.81)
            {
                isr= parseDouble(txtSalario.getText())-642.85;
                total= afp + isr;
                salario_final= parseDouble(txtSalario.getText()) - afp - isr;
                ob.setAfp(afp);
                ob.setIsr(isr);
                ob.setTotal(total);
                ob.setSalario_final(salario_final);
            }
            else if (parseDouble(txtSalario.getText())>=915.82 && parseDouble(txtSalario.getText())<=2058.67)
            {
                isr= parseDouble(txtSalario.getText())-915.81;
                total= afp + isr;
                salario_final= parseDouble(txtSalario.getText()) - afp - isr;
                ob.setAfp(afp);
                ob.setIsr(isr);
                ob.setTotal(total);
                ob.setSalario_final(salario_final);
            }
            else if (parseDouble(txtSalario.getText())>=2058.68)
            {
                isr= parseDouble(txtSalario.getText())-2058.67;
                total= afp + isr;
                salario_final= parseDouble(txtSalario.getText()) - afp - isr;
                ob.setAfp(afp);
                ob.setIsr(isr);
                ob.setTotal(total);
                ob.setSalario_final(salario_final);
            }
            if(obj.modificarCargo())
            {
                    obj.modificarCargo();     
                    ob.modificarDescuento();
                    JOptionPane.showMessageDialog(this, "Datos Modificados");
                    Limpiar();
                    LimpiarTabla();
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(this,"Verifique el nombre del cargo. Podría existir.");
                    }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
         if (JOptionPane.showConfirmDialog(null, "¿Desea realizar la operación?" , "WARNING/AVISO", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION)
       {
        cargos obj = new  cargos();
        claces.descuentos ob = new  claces.descuentos();
        int ide= Integer.parseInt(id.getText());
        obj.setId(ide);
        ob.setCargo(ide);
        if(obj.eliminarContacto())
        {
            obj.eliminarContacto();
            ob.eliminarDescuento();
            JOptionPane.showMessageDialog(this, "Datos Eliminados");
            Limpiar();
            LimpiarTabla();
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Hay datos con este registro en otra tabla");
            Limpiar();
            LimpiarTabla();
        }
       }
    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cargos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cargos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cargos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cargos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cargos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JLabel id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabla;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JFormattedTextField txtSalario;
    // End of variables declaration//GEN-END:variables
}
